# See doc/docker/README.md or https://github.com/instructure/canvas-lms/tree/master/doc/docker
version: '2'
services:
  web: &WEB
    build:
      context: .
    links:
      - postgres
      - redis
    environment:
      RAILS_ENV: development
      VIRTUAL_HOST: canvas
    ports:
      - "3000:80"
    extra_hosts:
      - "auth:10.200.10.1"

  # jobs:
  #   <<: *WEB
  #   command: bundle exec script/delayed_job run

  postgres:
    build: ./docker-compose/postgres

  redis:
    image: redis:2.6
